name: Build Dante on Multiple Linux Distros

on:
  push:
    paths:
      - 'dante/**'
      - '.github/workflows/build-multi-platform.yml'
  pull_request:
    paths:
      - 'dante/**'
      - '.github/workflows/build-multi-platform.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: ubuntu
            image: ubuntu:22.04
            install: apt-get update && apt-get install -y build-essential gcc make autoconf automake
          - name: debian
            image: debian:stable
            install: apt-get update && apt-get install -y build-essential gcc make autoconf automake
          - name: centos
            image: centos:7
            install: yum install -y gcc make autoconf automake
          - name: alpine
            image: alpine:latest
            install: apk add --no-cache build-base gcc make autoconf automake

    container:
      image: ${{ matrix.image }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install build tools
        run: ${{ matrix.install }}

      - name: Build dante
        run: |
          cd dante
          if [ -f ./configure ]; then
            chmod +x ./configure
            ./configure
          fi
          make
          ls -lsh

      - name: Upload dante binary artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dante-bin-${{ matrix.name }}
          path: |
            dante/*/sockd
            dante/*/sockd
            dante/sockd
            dante/sockd
